name: Run Clustering Script

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn

      - name: Run Python Script
        run: |
          python scripts/clustering_analysis.py
